server:
  port: 8010
  servlet:
    context-path: /api

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    host: localhost
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:3306/bored?useTimezone=true&serverTimezone=America/Belem&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:toor
  jpa:
    database: postgresql
    properties.hibernate:
      show_sql: true
      format_sql: true
  liquibase:
    url: ${spring.datasource.url}
    default-schema: bored
    change-log: classpath:/liquibase/liquibase-changelog.yml
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
